package com.mcs1205.parser.parsetree;

/**
 * Created by kasunp on 8/1/17.
 */
public enum PTNodeType {
    PROGRAM,
    TERMINAL,
    STATEMENT,
    STATEMENT_LIST,
    TERMINATED_STATEMENT,
    DECLARATION,
    EXPRESSION,
    ARITHMETIC_EXPRESSION,
    ALGEBRAIC_EXPRESSION,
    BOOLEAN_EXPRESSION,
    ASSIGNMENT_EXPRESSION,
    FOR_LOOP
}
